[erp_server_test]
13.61.25.90 ansible_user=ubuntu ansible_ssh_private_key_file=/home/frappe/.ssh/ansible.pem

[pnp_server]
13.61.105.20 ansible_user=ubuntu ansible_ssh_private_key_file=/home/frappe/.ssh/pnpgarment.pem

[teelan_server]
13.61.105.20 ansible_user=ubuntu ansible_ssh_private_key_file=/home/frappe/.ssh/pnpgarment.pem

; [ec2]
; app_server ansible_host=51.21.5.41

; [ec2:vars]
; ansible_user=ubuntu
; ansible_ssh_private_key_file=/home/frappe/.ssh/visiontech.pem
; ansible_python_interpreter=/usr/bin/python3
