- name: Add NodeSource repo
  shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

- name: Install NodeJS 18
  apt:
    name: nodejs
    update_cache: yes
    state: present

- name: Install yarn
  npm:
    name: yarn
    global: yes