- name: Update System 
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required packages
  apt: 
    name: 
      - git
      - curl
      - sudo 
      - python3-dev
      - python3.10-dev
      - python3-setuptools
      - python3-pip
      - python3-distutils
      - python3-venv
      - software-properties-common
      - mariadb-server
      - mariadb-client
      - redis-server
      - xvfb
      - libfontconfig
      - wkhtmltopdf
      - libmysqlclient-dev
      
    update_cache: yes
    state: present


# - name: Setup NGINX for ERPNext
#   shell: |
#     su - frappe -c "cd /home/frappe/frappe-bench && bench setup nginx"

# - name: Restart NGINX
#   service:
#     name: nginx
#     state: restarted
  
# - name: Restart all supervisor services
#   shell: supervisorctl restart all


# - name: Setup production mode
#   shell: |
#     su - frappe -c "cd /home/frappe/frappe-bench && bench setup production frappe"





